-- PostgreSQL baseline for the six persistence aggregates.  IDs are generated by
-- the application so this migration does not require superuser extensions.
CREATE TABLE departments (
    id UUID PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    student_count INTEGER NOT NULL DEFAULT 0 CHECK (student_count >= 0),
    instructor_count INTEGER NOT NULL DEFAULT 0 CHECK (instructor_count >= 0),
    course_count INTEGER NOT NULL DEFAULT 0 CHECK (course_count >= 0),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE students (
    id UUID PRIMARY KEY,
    student_number VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    department_id UUID NOT NULL REFERENCES departments(id),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','GRADUATED','SUSPENDED')),
    enrollment_history_count INTEGER NOT NULL DEFAULT 0 CHECK (enrollment_history_count >= 0),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE student_profiles (
    student_id UUID PRIMARY KEY REFERENCES students(id) ON DELETE CASCADE,
    phone VARCHAR(40),
    date_of_birth DATE,
    address VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE instructors (
    id UUID PRIMARY KEY,
    employee_number VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    department_id UUID NOT NULL REFERENCES departments(id),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE courses (
    id UUID PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    credits INTEGER NOT NULL CHECK (credits > 0),
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    occupied_seats INTEGER NOT NULL DEFAULT 0 CHECK (occupied_seats >= 0 AND occupied_seats <= capacity),
    department_id UUID NOT NULL REFERENCES departments(id),
    instructor_id UUID NOT NULL REFERENCES instructors(id),
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','OPEN','CLOSED','CANCELLED','COMPLETED')),
    enrollment_history_count INTEGER NOT NULL DEFAULT 0 CHECK (enrollment_history_count >= 0),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE enrollments (
    id UUID PRIMARY KEY,
    student_id UUID NOT NULL REFERENCES students(id),
    course_id UUID NOT NULL REFERENCES courses(id),
    status VARCHAR(16) NOT NULL CHECK (status IN ('ENROLLED','WAITLISTED','DROPPED','COMPLETED')),
    final_grade VARCHAR(32),
    enrolled_at TIMESTAMPTZ NOT NULL,
    dropped_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT enrollment_drop_consistency CHECK ((status = 'DROPPED') = (dropped_at IS NOT NULL)),
    CONSTRAINT enrollment_grade_consistency CHECK (final_grade IS NULL OR status = 'COMPLETED')
);

CREATE INDEX idx_students_department ON students(department_id);
CREATE INDEX idx_students_status ON students(status);
CREATE INDEX idx_instructors_department ON instructors(department_id);
CREATE INDEX idx_courses_department ON courses(department_id);
CREATE INDEX idx_courses_instructor ON courses(instructor_id);
CREATE INDEX idx_courses_status ON courses(status);
CREATE INDEX idx_enrollments_student ON enrollments(student_id, status);
CREATE INDEX idx_enrollments_course ON enrollments(course_id, status);
CREATE UNIQUE INDEX uq_active_student_course ON enrollments(student_id, course_id)
    WHERE status IN ('ENROLLED', 'WAITLISTED');
