CREATE TABLE migration_runs (
    id UUID PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    source VARCHAR(64) NOT NULL,
    target VARCHAR(64) NOT NULL,
    dry_run BOOLEAN NOT NULL,
    batch_size INTEGER NOT NULL CHECK (batch_size BETWEEN 1 AND 100),
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    error_summary VARCHAR(2000)
);

CREATE TABLE migration_checkpoints (
    run_id UUID NOT NULL REFERENCES migration_runs(id) ON DELETE CASCADE,
    entity_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    read_count BIGINT NOT NULL DEFAULT 0,
    insert_count BIGINT NOT NULL DEFAULT 0,
    skip_count BIGINT NOT NULL DEFAULT 0,
    failure_count BIGINT NOT NULL DEFAULT 0,
    last_processed_key VARCHAR(2000),
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (run_id, entity_type)
);

CREATE TABLE migration_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES migration_runs(id) ON DELETE CASCADE,
    entity_type VARCHAR(64),
    source_key VARCHAR(500),
    error_type VARCHAR(200) NOT NULL,
    error_message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_migration_runs_status ON migration_runs(status);
CREATE INDEX idx_migration_errors_run ON migration_errors(run_id);
