spring:
  application:
    name: student-portal-api

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
