spring:
  autoconfigure:
    exclude: ""
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost.localstack.cloud:5432/student_portal}
    username: ${POSTGRES_USER:student_portal}
    password: ${POSTGRES_PASSWORD:student_portal_local}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
